# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/student/Documents/GitHub/CTULib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/student/Documents/GitHub/CTULib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.2/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/student/Documents/GitHub/CTULib/CMakeFiles /Users/student/Documents/GitHub/CTULib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/student/Documents/GitHub/CTULib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CthulhuCore

# Build rule for target.
CthulhuCore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CthulhuCore
.PHONY : CthulhuCore

# fast build rule for target.
CthulhuCore/fast:
	$(MAKE) -f CMakeFiles/CthulhuCore.dir/build.make CMakeFiles/CthulhuCore.dir/build
.PHONY : CthulhuCore/fast

#=============================================================================
# Target rules for targets named CthulhuFileSystem

# Build rule for target.
CthulhuFileSystem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CthulhuFileSystem
.PHONY : CthulhuFileSystem

# fast build rule for target.
CthulhuFileSystem/fast:
	$(MAKE) -f CMakeFiles/CthulhuFileSystem.dir/build.make CMakeFiles/CthulhuFileSystem.dir/build
.PHONY : CthulhuFileSystem/fast

#=============================================================================
# Target rules for targets named WindowTest

# Build rule for target.
WindowTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WindowTest
.PHONY : WindowTest

# fast build rule for target.
WindowTest/fast:
	$(MAKE) -f CMakeFiles/WindowTest.dir/build.make CMakeFiles/WindowTest.dir/build
.PHONY : WindowTest/fast

#=============================================================================
# Target rules for targets named CthulhuGraphics

# Build rule for target.
CthulhuGraphics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CthulhuGraphics
.PHONY : CthulhuGraphics

# fast build rule for target.
CthulhuGraphics/fast:
	$(MAKE) -f CMakeFiles/CthulhuGraphics.dir/build.make CMakeFiles/CthulhuGraphics.dir/build
.PHONY : CthulhuGraphics/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

Cthulhu/Core/Collections/CthulhuString.o: Cthulhu/Core/Collections/CthulhuString.cpp.o

.PHONY : Cthulhu/Core/Collections/CthulhuString.o

# target to build an object file
Cthulhu/Core/Collections/CthulhuString.cpp.o:
	$(MAKE) -f CMakeFiles/CthulhuCore.dir/build.make CMakeFiles/CthulhuCore.dir/Cthulhu/Core/Collections/CthulhuString.cpp.o
.PHONY : Cthulhu/Core/Collections/CthulhuString.cpp.o

Cthulhu/Core/Collections/CthulhuString.i: Cthulhu/Core/Collections/CthulhuString.cpp.i

.PHONY : Cthulhu/Core/Collections/CthulhuString.i

# target to preprocess a source file
Cthulhu/Core/Collections/CthulhuString.cpp.i:
	$(MAKE) -f CMakeFiles/CthulhuCore.dir/build.make CMakeFiles/CthulhuCore.dir/Cthulhu/Core/Collections/CthulhuString.cpp.i
.PHONY : Cthulhu/Core/Collections/CthulhuString.cpp.i

Cthulhu/Core/Collections/CthulhuString.s: Cthulhu/Core/Collections/CthulhuString.cpp.s

.PHONY : Cthulhu/Core/Collections/CthulhuString.s

# target to generate assembly for a file
Cthulhu/Core/Collections/CthulhuString.cpp.s:
	$(MAKE) -f CMakeFiles/CthulhuCore.dir/build.make CMakeFiles/CthulhuCore.dir/Cthulhu/Core/Collections/CthulhuString.cpp.s
.PHONY : Cthulhu/Core/Collections/CthulhuString.cpp.s

Cthulhu/Core/Collections/Range.o: Cthulhu/Core/Collections/Range.cpp.o

.PHONY : Cthulhu/Core/Collections/Range.o

# target to build an object file
Cthulhu/Core/Collections/Range.cpp.o:
	$(MAKE) -f CMakeFiles/CthulhuCore.dir/build.make CMakeFiles/CthulhuCore.dir/Cthulhu/Core/Collections/Range.cpp.o
.PHONY : Cthulhu/Core/Collections/Range.cpp.o

Cthulhu/Core/Collections/Range.i: Cthulhu/Core/Collections/Range.cpp.i

.PHONY : Cthulhu/Core/Collections/Range.i

# target to preprocess a source file
Cthulhu/Core/Collections/Range.cpp.i:
	$(MAKE) -f CMakeFiles/CthulhuCore.dir/build.make CMakeFiles/CthulhuCore.dir/Cthulhu/Core/Collections/Range.cpp.i
.PHONY : Cthulhu/Core/Collections/Range.cpp.i

Cthulhu/Core/Collections/Range.s: Cthulhu/Core/Collections/Range.cpp.s

.PHONY : Cthulhu/Core/Collections/Range.s

# target to generate assembly for a file
Cthulhu/Core/Collections/Range.cpp.s:
	$(MAKE) -f CMakeFiles/CthulhuCore.dir/build.make CMakeFiles/CthulhuCore.dir/Cthulhu/Core/Collections/Range.cpp.s
.PHONY : Cthulhu/Core/Collections/Range.cpp.s

Cthulhu/Core/Serialization/JSON.o: Cthulhu/Core/Serialization/JSON.cpp.o

.PHONY : Cthulhu/Core/Serialization/JSON.o

# target to build an object file
Cthulhu/Core/Serialization/JSON.cpp.o:
	$(MAKE) -f CMakeFiles/CthulhuCore.dir/build.make CMakeFiles/CthulhuCore.dir/Cthulhu/Core/Serialization/JSON.cpp.o
.PHONY : Cthulhu/Core/Serialization/JSON.cpp.o

Cthulhu/Core/Serialization/JSON.i: Cthulhu/Core/Serialization/JSON.cpp.i

.PHONY : Cthulhu/Core/Serialization/JSON.i

# target to preprocess a source file
Cthulhu/Core/Serialization/JSON.cpp.i:
	$(MAKE) -f CMakeFiles/CthulhuCore.dir/build.make CMakeFiles/CthulhuCore.dir/Cthulhu/Core/Serialization/JSON.cpp.i
.PHONY : Cthulhu/Core/Serialization/JSON.cpp.i

Cthulhu/Core/Serialization/JSON.s: Cthulhu/Core/Serialization/JSON.cpp.s

.PHONY : Cthulhu/Core/Serialization/JSON.s

# target to generate assembly for a file
Cthulhu/Core/Serialization/JSON.cpp.s:
	$(MAKE) -f CMakeFiles/CthulhuCore.dir/build.make CMakeFiles/CthulhuCore.dir/Cthulhu/Core/Serialization/JSON.cpp.s
.PHONY : Cthulhu/Core/Serialization/JSON.cpp.s

Cthulhu/Core/Standard/Exit.o: Cthulhu/Core/Standard/Exit.cpp.o

.PHONY : Cthulhu/Core/Standard/Exit.o

# target to build an object file
Cthulhu/Core/Standard/Exit.cpp.o:
	$(MAKE) -f CMakeFiles/CthulhuCore.dir/build.make CMakeFiles/CthulhuCore.dir/Cthulhu/Core/Standard/Exit.cpp.o
.PHONY : Cthulhu/Core/Standard/Exit.cpp.o

Cthulhu/Core/Standard/Exit.i: Cthulhu/Core/Standard/Exit.cpp.i

.PHONY : Cthulhu/Core/Standard/Exit.i

# target to preprocess a source file
Cthulhu/Core/Standard/Exit.cpp.i:
	$(MAKE) -f CMakeFiles/CthulhuCore.dir/build.make CMakeFiles/CthulhuCore.dir/Cthulhu/Core/Standard/Exit.cpp.i
.PHONY : Cthulhu/Core/Standard/Exit.cpp.i

Cthulhu/Core/Standard/Exit.s: Cthulhu/Core/Standard/Exit.cpp.s

.PHONY : Cthulhu/Core/Standard/Exit.s

# target to generate assembly for a file
Cthulhu/Core/Standard/Exit.cpp.s:
	$(MAKE) -f CMakeFiles/CthulhuCore.dir/build.make CMakeFiles/CthulhuCore.dir/Cthulhu/Core/Standard/Exit.cpp.s
.PHONY : Cthulhu/Core/Standard/Exit.cpp.s

Cthulhu/Core/Types/Errno.o: Cthulhu/Core/Types/Errno.cpp.o

.PHONY : Cthulhu/Core/Types/Errno.o

# target to build an object file
Cthulhu/Core/Types/Errno.cpp.o:
	$(MAKE) -f CMakeFiles/CthulhuCore.dir/build.make CMakeFiles/CthulhuCore.dir/Cthulhu/Core/Types/Errno.cpp.o
.PHONY : Cthulhu/Core/Types/Errno.cpp.o

Cthulhu/Core/Types/Errno.i: Cthulhu/Core/Types/Errno.cpp.i

.PHONY : Cthulhu/Core/Types/Errno.i

# target to preprocess a source file
Cthulhu/Core/Types/Errno.cpp.i:
	$(MAKE) -f CMakeFiles/CthulhuCore.dir/build.make CMakeFiles/CthulhuCore.dir/Cthulhu/Core/Types/Errno.cpp.i
.PHONY : Cthulhu/Core/Types/Errno.cpp.i

Cthulhu/Core/Types/Errno.s: Cthulhu/Core/Types/Errno.cpp.s

.PHONY : Cthulhu/Core/Types/Errno.s

# target to generate assembly for a file
Cthulhu/Core/Types/Errno.cpp.s:
	$(MAKE) -f CMakeFiles/CthulhuCore.dir/build.make CMakeFiles/CthulhuCore.dir/Cthulhu/Core/Types/Errno.cpp.s
.PHONY : Cthulhu/Core/Types/Errno.cpp.s

Cthulhu/FileSystem/FastFile.o: Cthulhu/FileSystem/FastFile.cpp.o

.PHONY : Cthulhu/FileSystem/FastFile.o

# target to build an object file
Cthulhu/FileSystem/FastFile.cpp.o:
	$(MAKE) -f CMakeFiles/CthulhuFileSystem.dir/build.make CMakeFiles/CthulhuFileSystem.dir/Cthulhu/FileSystem/FastFile.cpp.o
.PHONY : Cthulhu/FileSystem/FastFile.cpp.o

Cthulhu/FileSystem/FastFile.i: Cthulhu/FileSystem/FastFile.cpp.i

.PHONY : Cthulhu/FileSystem/FastFile.i

# target to preprocess a source file
Cthulhu/FileSystem/FastFile.cpp.i:
	$(MAKE) -f CMakeFiles/CthulhuFileSystem.dir/build.make CMakeFiles/CthulhuFileSystem.dir/Cthulhu/FileSystem/FastFile.cpp.i
.PHONY : Cthulhu/FileSystem/FastFile.cpp.i

Cthulhu/FileSystem/FastFile.s: Cthulhu/FileSystem/FastFile.cpp.s

.PHONY : Cthulhu/FileSystem/FastFile.s

# target to generate assembly for a file
Cthulhu/FileSystem/FastFile.cpp.s:
	$(MAKE) -f CMakeFiles/CthulhuFileSystem.dir/build.make CMakeFiles/CthulhuFileSystem.dir/Cthulhu/FileSystem/FastFile.cpp.s
.PHONY : Cthulhu/FileSystem/FastFile.cpp.s

Cthulhu/FileSystem/File.o: Cthulhu/FileSystem/File.cpp.o

.PHONY : Cthulhu/FileSystem/File.o

# target to build an object file
Cthulhu/FileSystem/File.cpp.o:
	$(MAKE) -f CMakeFiles/CthulhuFileSystem.dir/build.make CMakeFiles/CthulhuFileSystem.dir/Cthulhu/FileSystem/File.cpp.o
.PHONY : Cthulhu/FileSystem/File.cpp.o

Cthulhu/FileSystem/File.i: Cthulhu/FileSystem/File.cpp.i

.PHONY : Cthulhu/FileSystem/File.i

# target to preprocess a source file
Cthulhu/FileSystem/File.cpp.i:
	$(MAKE) -f CMakeFiles/CthulhuFileSystem.dir/build.make CMakeFiles/CthulhuFileSystem.dir/Cthulhu/FileSystem/File.cpp.i
.PHONY : Cthulhu/FileSystem/File.cpp.i

Cthulhu/FileSystem/File.s: Cthulhu/FileSystem/File.cpp.s

.PHONY : Cthulhu/FileSystem/File.s

# target to generate assembly for a file
Cthulhu/FileSystem/File.cpp.s:
	$(MAKE) -f CMakeFiles/CthulhuFileSystem.dir/build.make CMakeFiles/CthulhuFileSystem.dir/Cthulhu/FileSystem/File.cpp.s
.PHONY : Cthulhu/FileSystem/File.cpp.s

Cthulhu/Graphics/Darwin/View.o: Cthulhu/Graphics/Darwin/View.mm.o

.PHONY : Cthulhu/Graphics/Darwin/View.o

# target to build an object file
Cthulhu/Graphics/Darwin/View.mm.o:
	$(MAKE) -f CMakeFiles/CthulhuGraphics.dir/build.make CMakeFiles/CthulhuGraphics.dir/Cthulhu/Graphics/Darwin/View.mm.o
.PHONY : Cthulhu/Graphics/Darwin/View.mm.o

Cthulhu/Graphics/Darwin/View.i: Cthulhu/Graphics/Darwin/View.mm.i

.PHONY : Cthulhu/Graphics/Darwin/View.i

# target to preprocess a source file
Cthulhu/Graphics/Darwin/View.mm.i:
	$(MAKE) -f CMakeFiles/CthulhuGraphics.dir/build.make CMakeFiles/CthulhuGraphics.dir/Cthulhu/Graphics/Darwin/View.mm.i
.PHONY : Cthulhu/Graphics/Darwin/View.mm.i

Cthulhu/Graphics/Darwin/View.s: Cthulhu/Graphics/Darwin/View.mm.s

.PHONY : Cthulhu/Graphics/Darwin/View.s

# target to generate assembly for a file
Cthulhu/Graphics/Darwin/View.mm.s:
	$(MAKE) -f CMakeFiles/CthulhuGraphics.dir/build.make CMakeFiles/CthulhuGraphics.dir/Cthulhu/Graphics/Darwin/View.mm.s
.PHONY : Cthulhu/Graphics/Darwin/View.mm.s

Cthulhu/Graphics/Darwin/Window.o: Cthulhu/Graphics/Darwin/Window.mm.o

.PHONY : Cthulhu/Graphics/Darwin/Window.o

# target to build an object file
Cthulhu/Graphics/Darwin/Window.mm.o:
	$(MAKE) -f CMakeFiles/CthulhuGraphics.dir/build.make CMakeFiles/CthulhuGraphics.dir/Cthulhu/Graphics/Darwin/Window.mm.o
.PHONY : Cthulhu/Graphics/Darwin/Window.mm.o

Cthulhu/Graphics/Darwin/Window.i: Cthulhu/Graphics/Darwin/Window.mm.i

.PHONY : Cthulhu/Graphics/Darwin/Window.i

# target to preprocess a source file
Cthulhu/Graphics/Darwin/Window.mm.i:
	$(MAKE) -f CMakeFiles/CthulhuGraphics.dir/build.make CMakeFiles/CthulhuGraphics.dir/Cthulhu/Graphics/Darwin/Window.mm.i
.PHONY : Cthulhu/Graphics/Darwin/Window.mm.i

Cthulhu/Graphics/Darwin/Window.s: Cthulhu/Graphics/Darwin/Window.mm.s

.PHONY : Cthulhu/Graphics/Darwin/Window.s

# target to generate assembly for a file
Cthulhu/Graphics/Darwin/Window.mm.s:
	$(MAKE) -f CMakeFiles/CthulhuGraphics.dir/build.make CMakeFiles/CthulhuGraphics.dir/Cthulhu/Graphics/Darwin/Window.mm.s
.PHONY : Cthulhu/Graphics/Darwin/Window.mm.s

Cthulhu/Graphics/Types.o: Cthulhu/Graphics/Types.cpp.o

.PHONY : Cthulhu/Graphics/Types.o

# target to build an object file
Cthulhu/Graphics/Types.cpp.o:
	$(MAKE) -f CMakeFiles/CthulhuGraphics.dir/build.make CMakeFiles/CthulhuGraphics.dir/Cthulhu/Graphics/Types.cpp.o
.PHONY : Cthulhu/Graphics/Types.cpp.o

Cthulhu/Graphics/Types.i: Cthulhu/Graphics/Types.cpp.i

.PHONY : Cthulhu/Graphics/Types.i

# target to preprocess a source file
Cthulhu/Graphics/Types.cpp.i:
	$(MAKE) -f CMakeFiles/CthulhuGraphics.dir/build.make CMakeFiles/CthulhuGraphics.dir/Cthulhu/Graphics/Types.cpp.i
.PHONY : Cthulhu/Graphics/Types.cpp.i

Cthulhu/Graphics/Types.s: Cthulhu/Graphics/Types.cpp.s

.PHONY : Cthulhu/Graphics/Types.s

# target to generate assembly for a file
Cthulhu/Graphics/Types.cpp.s:
	$(MAKE) -f CMakeFiles/CthulhuGraphics.dir/build.make CMakeFiles/CthulhuGraphics.dir/Cthulhu/Graphics/Types.cpp.s
.PHONY : Cthulhu/Graphics/Types.cpp.s

Programs/Tests/Engine/Window.o: Programs/Tests/Engine/Window.cpp.o

.PHONY : Programs/Tests/Engine/Window.o

# target to build an object file
Programs/Tests/Engine/Window.cpp.o:
	$(MAKE) -f CMakeFiles/WindowTest.dir/build.make CMakeFiles/WindowTest.dir/Programs/Tests/Engine/Window.cpp.o
.PHONY : Programs/Tests/Engine/Window.cpp.o

Programs/Tests/Engine/Window.i: Programs/Tests/Engine/Window.cpp.i

.PHONY : Programs/Tests/Engine/Window.i

# target to preprocess a source file
Programs/Tests/Engine/Window.cpp.i:
	$(MAKE) -f CMakeFiles/WindowTest.dir/build.make CMakeFiles/WindowTest.dir/Programs/Tests/Engine/Window.cpp.i
.PHONY : Programs/Tests/Engine/Window.cpp.i

Programs/Tests/Engine/Window.s: Programs/Tests/Engine/Window.cpp.s

.PHONY : Programs/Tests/Engine/Window.s

# target to generate assembly for a file
Programs/Tests/Engine/Window.cpp.s:
	$(MAKE) -f CMakeFiles/WindowTest.dir/build.make CMakeFiles/WindowTest.dir/Programs/Tests/Engine/Window.cpp.s
.PHONY : Programs/Tests/Engine/Window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... CthulhuCore"
	@echo "... CthulhuFileSystem"
	@echo "... WindowTest"
	@echo "... edit_cache"
	@echo "... CthulhuGraphics"
	@echo "... doc"
	@echo "... Cthulhu/Core/Collections/CthulhuString.o"
	@echo "... Cthulhu/Core/Collections/CthulhuString.i"
	@echo "... Cthulhu/Core/Collections/CthulhuString.s"
	@echo "... Cthulhu/Core/Collections/Range.o"
	@echo "... Cthulhu/Core/Collections/Range.i"
	@echo "... Cthulhu/Core/Collections/Range.s"
	@echo "... Cthulhu/Core/Serialization/JSON.o"
	@echo "... Cthulhu/Core/Serialization/JSON.i"
	@echo "... Cthulhu/Core/Serialization/JSON.s"
	@echo "... Cthulhu/Core/Standard/Exit.o"
	@echo "... Cthulhu/Core/Standard/Exit.i"
	@echo "... Cthulhu/Core/Standard/Exit.s"
	@echo "... Cthulhu/Core/Types/Errno.o"
	@echo "... Cthulhu/Core/Types/Errno.i"
	@echo "... Cthulhu/Core/Types/Errno.s"
	@echo "... Cthulhu/FileSystem/FastFile.o"
	@echo "... Cthulhu/FileSystem/FastFile.i"
	@echo "... Cthulhu/FileSystem/FastFile.s"
	@echo "... Cthulhu/FileSystem/File.o"
	@echo "... Cthulhu/FileSystem/File.i"
	@echo "... Cthulhu/FileSystem/File.s"
	@echo "... Cthulhu/Graphics/Darwin/View.o"
	@echo "... Cthulhu/Graphics/Darwin/View.i"
	@echo "... Cthulhu/Graphics/Darwin/View.s"
	@echo "... Cthulhu/Graphics/Darwin/Window.o"
	@echo "... Cthulhu/Graphics/Darwin/Window.i"
	@echo "... Cthulhu/Graphics/Darwin/Window.s"
	@echo "... Cthulhu/Graphics/Types.o"
	@echo "... Cthulhu/Graphics/Types.i"
	@echo "... Cthulhu/Graphics/Types.s"
	@echo "... Programs/Tests/Engine/Window.o"
	@echo "... Programs/Tests/Engine/Window.i"
	@echo "... Programs/Tests/Engine/Window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

